spring:
  datasource:
    url: jdbc:mysql://localhost:3306/financial_engine?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: dbuser
    password: dbpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        isolation: 4 # REPEATABLE_READ
server:
  port: 8080
